name: Docker Stack Deployment
author: Tristiisch <tristiisch@outlook.fr>
description: A GitHub Action that supports docker-compose and Docker Swarm deployments
inputs:
  remote_docker_host:
    description: 'Remote Docker host (e.g., 127.0.0.1)'
    required: true
  remote_docker_port:
    description: 'Remote Docker SSH port (default: 22)'
    default: 22
  remote_docker_username:
    description: 'Remote Docker username (e.g., baptiste)'
    required: true
  ssh_public_key:
    description: 'Public key of the SSH server'
    required: true
  ssh_private_key:
    description: 'Private key of the SSH client'
    required: true
  deployment_mode:
    description: 'Deployment mode: docker-swarm or docker-compose (default: docker-compose)'
    default: './docker-compose'
  copy_stack_file:
    description: 'Copy stack file to remote server and deploy from the server (default: false)'
  deploy_path:
    description: 'Path where stack files will be copied (default: ~/docker-deployment)'
  stack_file_path:
    description: 'Path to Docker stack file (default: docker-compose.yaml)'
  keep_files:
    description: 'Number of files to keep on the server (default: 3)'
    default: 3
  docker_prune:
    description: 'Trigger docker prune command (default: false)'
    default: false
  docker_remove_orphans:
    description: 'Remove containers for services not defined in the Compose file (default: true)'
    default: true
  pre_deployment_command_args:
    description: '[Docker Compose] Arguments for the pre-deployment command'
  pull_images_first:
    description: '[Docker Compose] Pull Docker images before deploying'
  stack_name:
    description: '[Docker Swarm] Specify the name of your Docker Swarm stack.'
  deploy_foreground:
    description: '[Docker Swarm] Waiting for the stack to complete the rolling update.'
    default: true
  secrets:
    description: 'Update Docker Secret using rotation during Stack Update. Format is service_name secret_name key1 value1 key2 value2 ...'
  args:
    description: 'Command arguments for deployment'
  debug:
    description: 'Enable debug mode to include additional debugging messages (default: true)'
    default: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: send
  color: green
