name: Deployement Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, synchronize]
    branches:
      - "*"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: ./.github/workflows/setup
    - name: Start Deployment 1 - Basic
      uses: ./
      with:
        deployment_mode: docker-swarm
        remote_docker_host: "${{ steps.w8_for_sshd.outputs.container_name }}"
        remote_docker_port: "${{ env.CONTAINER_SSH_PORT }}"
        remote_docker_username: "${{ env.REMOTE_SSH_USER }}"
        ssh_private_key: "${{ steps.generate_ssh_private_key.outputs.value }}"
        ssh_public_key: "${{ steps.get_ssh_public_key.outputs.env.value }}"
        stack_file_path: ./tests/docker-compose.yml
        stack_name: nginx_1

  job2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: ./.github/workflows/setup
    - name: Start Deployment 2 - No pub key
      uses: ./
      with:
        deployment_mode: docker-swarm
        remote_docker_host: "${{ steps.w8_for_sshd.outputs.container_name }}"
        remote_docker_port: "${{ env.CONTAINER_SSH_PORT }}"
        remote_docker_username: "${{ env.REMOTE_SSH_USER }}"
        ssh_private_key: "${{ steps.generate_ssh_private_key.outputs.value }}"
        stack_file_path: ./tests/docker-compose.yml
        stack_name: nginx_2

  job3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: ./.github/workflows/setup
    - name: Start Deployment 3 - Background deploy
      uses: ./
      with:
        deployment_mode: docker-swarm
        remote_docker_host: "${{ steps.w8_for_sshd.outputs.container_name }}"
        remote_docker_port: "${{ env.CONTAINER_SSH_PORT }}"
        remote_docker_username: "${{ env.REMOTE_SSH_USER }}"
        ssh_private_key: "${{ steps.generate_ssh_private_key.outputs.value }}"
        ssh_public_key: "${{ steps.get_ssh_public_key.outputs.env.value }}"
        stack_file_path: ./tests/docker-compose.yml
        stack_name: nginx_3
        deploy_foreground: false

  job4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: ./.github/workflows/setup
    - name: Start Deployment 4 - Debug
      uses: ./
      with:
        deployment_mode: docker-swarm
        remote_docker_host: "${{ steps.w8_for_sshd.outputs.container_name }}"
        remote_docker_port: "${{ env.CONTAINER_SSH_PORT }}"
        remote_docker_username: "${{ env.REMOTE_SSH_USER }}"
        ssh_private_key: "${{ steps.generate_ssh_private_key.outputs.value }}"
        ssh_public_key: "${{ steps.get_ssh_public_key.outputs.env.value }}"
        stack_file_path: ./tests/docker-compose.yml
        stack_name: nginx_4
        debug: true
