name: Example usage

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_KEY_TYPE: "ed25519"
      SSH_KEY_PATH: "$HOME/.ssh/id_ed25519"
      SSH_PORT: "2222"
      REMOTE_USER: "president"
      REMOTE_HOST: "localhost:2222"
      REMOTE_HOST_PASSWORD: "P@ssword!"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Build a Docker image with ssh & docker
      run: docker build -f tests/Dockerfile -t docker_throw_ssh .

    - name: Start an SSH server in a Docker container
      run: |
        docker run -d \
          -p ${{ env.SSH_PORT }}:22 \
          --name docker-throw-ssh \
          --privileged \
          --rm \
          --cpus="1" --memory="1g" \
          docker_throw_ssh

    - name: Generate an ssh-key
      run: |
        ssh-keygen -t "${{ env.SSH_KEY_TYPE }}" -f "${{ env.SSH_KEY_PATH }}" -N "" -o -a 100
        echo "SSH_KEY_PUBLIC=$(cat \"${{ env.SSH_KEY_PATH }}.pub\")" >> $GITHUB_ENV

    - name: Start an SSH server in a Docker container
      run: |
        apt install -y sshpass
        sshpass -p "${{ env.REMOTE_HOST_PASSWORD }}" ssh-copy-id -o StrictHostKeyChecking=no -i "${{ env.SSH_KEY_PATH }}" "${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}"

    - name: Retrieve SSH Public Key
      id: get_key
      run: |
        PUBLIC_KEY=$(ssh-keyscan -t "${{ env.SSH_KEY_TYPE }}" remote_host)
        echo "SSH_PUBLIC_KEY=${PUBLIC_KEY}" >> $GITHUB_ENV

    - name: Start Deployment 1
      uses: tristiisch/docker-stack-deployment@v2.1
      with:
        deployment_mode: docker-swarm
        remote_docker_host: ${{ env.REMOTE_HOST }}
        remote_docker_username: ${{ env.REMOTE_USER }}
        ssh_private_key: ${{ env.SSH_KEY_PUBLIC }}
        ssh_public_key: ${{ env.SSH_PUBLIC_KEY }}
        stack_file_path: ./tests/docker-compose.yml
        stack_name: nginx_1
